name: Release
on:
  workflow_dispatch: # Manual trigger alone

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Publish to npmjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get npm Package node-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
